// <auto-generated />
using System;
using BackendInfoApp.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendInfoApp.Migrations
{
    [DbContext(typeof(InfoAppDbContext))]
    partial class InfoAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Entities.WeatherDataEntity", b =>
                {
                    b.Property<int>("nId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nId"));

                    b.Property<double>("dFeelsLikeC")
                        .HasColumnType("double precision");

                    b.Property<double>("dTempC")
                        .HasColumnType("double precision");

                    b.Property<double>("dWindKph")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("oRecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("sCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sConditionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sWindDir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nId");

                    b.ToTable("WeatherData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
